export const ADD_DRIVERS = "ADD_DRIVERS";
export const ADD_CONSTRUCTORS = "ADD_CONSTRUCTORS";
export const DRIVERS_LOADING = "DRIVERS_LOADING";
export const CONSTRUCTORS_LOADING = "CONSTRUCTORS_LOADING";
export const DRIVERS_FAILED = "DRIVERS_FAILED";
export const CONSTRUCTORS_FAILED = "CONSTRUCTORS_FAILED";
